// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxeglgdcrfpfgtdexeje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4ZWdsZ2RjcmZwZmd0ZGV4ZWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTk4NzksImV4cCI6MjA2MzMzNTg3OX0.mWvq4s8dNzgodk8QOr05qigkprjpBAGhQ-KcWDnj7UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);